from docx import Document
from docx.shared import Pt

doc = Document()

# Title
doc.add_heading('Project Documentation — Full Data Science Project (Task-4)', level=1)

# Overview
doc.add_heading('Overview', level=2)
p = doc.add_paragraph()
p.add_run('This document summarizes the Task-4 project: an end-to-end data science pipeline that includes data preprocessing, model training, a FastAPI service, and a frontend demo. The repository contains serialized artifacts, training scripts, API source, and presentation materials.').font.size = Pt(11)

# Project Structure
doc.add_heading('Repository Structure', level=2)
items = [
    ('Presentation-and-Documentation/', 'Presentations, certificates, and documentation (includes generated PPTX and this DOCX).'),
    ('Task-4-Full-DS-Project/src/', 'Source code for preprocessing, training, and API (FastAPI app).'),
    ('models/', 'Serialized models and preprocessor artifacts used at inference.'),
    ('frontend/', 'Static UI files served at /ui for demo and batch upload.'),
]
for path, desc in items:
    p = doc.add_paragraph(style='List Bullet')
    p.add_run(path + ': ').bold = True
    p.add_run(desc)

# How to run locally
doc.add_heading('Running Locally', level=2)
doc.add_paragraph('Prerequisites: Python 3.10+, create and activate the project venv and install dependencies from requirements.txt. Use the provided venv if available.')
code_block = doc.add_paragraph()
code_block.add_run('PowerShell commands:').bold = True
cmds = [
    'cd "e:\\ProjectsGithub\\Data Science Internship"',
    '& ".venv/Scripts/Activate.ps1"',
    'pip install -r requirements.txt',
    'python -m src.train  # trains models and saves artifacts to models/' ,
    '& ".venv/Scripts/python.exe" -m uvicorn src.api:app --reload --host 0.0.0.0 --port 8000',
]
for c in cmds:
    p = doc.add_paragraph(style='Intense Quote')
    p.add_run(c).font.size = Pt(10)

# API Endpoints
doc.add_heading('API Endpoints', level=2)
doc.add_paragraph('/health — GET: returns service health and model load status')
doc.add_paragraph('/predict — POST: single-record prediction (JSON payload)')
doc.add_paragraph('/batch-predict — POST: upload CSV for batch predictions')
doc.add_paragraph('/model-info — GET: returns model metadata and feature list')

# Preprocessor & Models
doc.add_heading('Preprocessor & Models', level=2)
doc.add_paragraph('The project serializes an AdvancedPreprocessor (preprocessing pipeline) and multiple model artifacts (XGBoost, LightGBM, CatBoost, RandomForest). Ensure the preprocessor is loaded at inference to maintain feature consistency.')

# Testing & Debugging
doc.add_heading('Testing & Debugging', level=2)
doc.add_paragraph('Debug helper scripts exist in the repo to validate unpickling and API loading. Use these to reproduce loading errors and validate artifacts before deployment.')

# Deployment
doc.add_heading('Deployment Recommendations', level=2)
doc.add_paragraph('Containerize the FastAPI app with the included Dockerfile and use docker-compose for local orchestration. Add CI to run training tests and API smoke tests on push.')

# Next Steps
doc.add_heading('Next Steps', level=2)
ns = [
    'Train on real Bangalore housing dataset and persist updated artifacts.',
    'Add CI and unit/integration tests for the API and training pipelines.',
    'Implement model monitoring and automated retraining pipelines.'
]
for t in ns:
    p = doc.add_paragraph(style='List Bullet')
    p.add_run(t)

# Footer
doc.add_paragraph('\nGenerated by automation script.').italic = True
out_path = 'Presentation-and-Documentation/Project_Documentation.docx'
doc.save(out_path)
print('saved', out_path)
